"""empty message

Revision ID: 76882dce1f70
Revises: 
Create Date: 2018-12-06 15:43:43.204771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76882dce1f70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_requests')
    op.drop_table('stock_requests')
    # ### end Alembic commands ###
